org: samuelmalaga
app: sls-basics
service: sls-basics
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

functions:
  function1:
    handler: index.handler
    description: Minha primeira lambda exemplo
